# Generated by Django 5.0.6 on 2024-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceSite_django_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5),
        ),
    ]
