# Generated by Django 5.0.6 on 2024-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceSite_django_app', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
