# Generated by Django 5.0.6 on 2024-08-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceSite_django_app', '0004_alter_userprofile_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
